config/routes.rb
Rails.application.routes.draw do
  # devise_for :user, skip: :all, controllers: { passwords: 'passwords' }
  # devise_scope :user do
  #   post 'login', to: 'devise/sessions#create', as: :user_session
  #   delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  #   post 'sign_in', to: 'devise/registrations#create', as: :user_registration
  #   get 'password/edit', to: 'users/passwords#edit', as: :edit_user_password
  #   patch 'password/edit', to: 'users/passwords#update'
  #   put 'password/edit', to: 'users/passwords#update'
  #   post 'password/edit', to: 'users/passwords#create',as: :user_password
  # end

  devise_for :users
  #devise パスワードを忘れた場合のメール処理
  if Rails.env.development? || Rails.env.staging?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :clips, only: [:create, :destroy]
  end
  post '/posts/track', to: 'posts#track'
  get '/all_index', to: 'posts#all_index'
  resources :user
  resources :relationships, only: [:create,:destroy]
  resources :comments , only: [:create, :destroy]
  get 'user/:id/following', to: 'user#following', as: :user_following
  get 'user/:id/follower', to: 'user#follower', as: :user_follower
  get 'user/:id/like', to: 'user#like', as: :user_like
  get 'user/:id/clip', to: 'user#clip', as: :user_clip
  get 'rankings/post_ranking', to: 'rankings#post_ranking'
  get 'rankings/user_ranking', to: 'rankings#user_ranking'
  get 'searches/index', to: 'searches#index'
  get 'searches/more_posts', to: 'searches#more_posts'
  get 'searches/more_users', to: 'searches#more_users'
  get 'notifications/index', to: 'notifications#index'
  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get '/rules', to: 'policies#rules'
  get '/policy', to: 'policies#privacypolicy'
end

app/models/clip.rb
class Clip < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/controllers/clips_controller.rb
class ClipsController < ApplicationController
  after_action :create_notifications, only: [:create]

  def create
    return if Clip.exists?(user_id: current_user.id, post_id: params[:post_id])
    @clip = Clip.new(user_id: current_user.id, post_id: params[:post_id])
    @post = Post.find_by(id: @clip.post_id)
    if @clip.save
      respond_to do |format|
        format.js
      end
    else
      render nothing: true, status: 404
    end
  end

  def destroy
    @clip = Clip.find_by(user_id: current_user.id, post_id: params[:post_id])
    @post = Post.find_by(id: @clip.post_id)
    if @clip.destroy
      notification = Notification.find_by(user_id: @post.user_id, post_id: @post.id, notified_by_id: current_user.id, notified_type: "clip")
      if notification
        notification.destroy
      end
      respond_to do |format|
        format.js
      end
    else
      render nothing: true, status: 404
    end
  end

  private

  def create_notifications
    post = Post.find(params[:post_id])

    return if post.user_id == current_user.id
    Notification.create(user_id: post.user_id, post_id: post.id, notified_by_id: current_user.id, notified_type: "clip")
  end
end

app/views/clips/_clip.html.erb
<div class="like-clip-btn" id="id_clip-<%= post.id %>">
  <!-- ユーザがログインしている場合-->
  <% if user_signed_in? %>
    <!-- 投稿をすでにクリップしている場合-->
    <% if post.clips.find_by(user_id: current_user.id) %>
      <p class="change_to_unclip">
        <%= link_to post_clip_path(post.clips.find_by(user_id: current_user.id), post_id: post.id), method: :delete, remote: true do %>
          <!-- このボタンを押すとClip -> Unclipになる -->
          <i class="fas fa-paperclip text-orange"></i>
          <p class="count-beside-btn text-orange"><%= Clip.where(post_id: post.id).count %></p>
        <% end %>
      </p>
    <% else %>
      <!-- 投稿をまだクリップしていない場合-->
      <p class="change_to_clip">
        <%= link_to post_clips_path(post_id: post.id), method: :post, remote: true do %>
          <!-- このボタンを押すとUnclip -> Clipになる -->
          <i class="fas fa-paperclip"></i>
          <p class="count-beside-btn"><%= Clip.where(post_id: post.id).count %></p>
        <% end %>
      </p>
    <% end %>
  <!-- ユーザがログインしていない場合-->
  <% else %>
    <i class="fas fa-paperclip"><p class="count-beside-btn"><%= Clip.where(post_id: post.id).count %></p></i>
  <% end %>
</div>

app/views/clips/create.js.erb
$("#id_clip-<%= @post.id %>").html("<%= j(render partial: 'clip', locals: { clip: @clip, post: @post }) %>")

app/views/clips/destroy.js.erb
$("#id_clip-<%= @post.id %>").html("<%= j(render partial: 'clip', locals: { post: @post } ) %>")