config/routes.rb
Rails.application.routes.draw do
  # devise_for :user, skip: :all, controllers: { passwords: 'passwords' }
  # devise_scope :user do
  #   post 'login', to: 'devise/sessions#create', as: :user_session
  #   delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  #   post 'sign_in', to: 'devise/registrations#create', as: :user_registration
  #   get 'password/edit', to: 'users/passwords#edit', as: :edit_user_password
  #   patch 'password/edit', to: 'users/passwords#update'
  #   put 'password/edit', to: 'users/passwords#update'
  #   post 'password/edit', to: 'users/passwords#create',as: :user_password
  # end

  devise_for :users
  #devise パスワードを忘れた場合のメール処理
  if Rails.env.development? || Rails.env.staging?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :clips, only: [:create, :destroy]
  end
  post '/posts/track', to: 'posts#track'
  get '/all_index', to: 'posts#all_index'
  resources :user
  resources :relationships, only: [:create,:destroy]
  resources :comments , only: [:create, :destroy]
  get 'user/:id/following', to: 'user#following', as: :user_following
  get 'user/:id/follower', to: 'user#follower', as: :user_follower
  get 'user/:id/like', to: 'user#like', as: :user_like
  get 'user/:id/clip', to: 'user#clip', as: :user_clip
  get 'rankings/post_ranking', to: 'rankings#post_ranking'
  get 'rankings/user_ranking', to: 'rankings#user_ranking'
  get 'searches/index', to: 'searches#index'
  get 'searches/more_posts', to: 'searches#more_posts'
  get 'searches/more_users', to: 'searches#more_users'
  get 'notifications/index', to: 'notifications#index'
  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get '/rules', to: 'policies#rules'
  get '/policy', to: 'policies#privacypolicy'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable
  has_many :posts, dependent: :destroy

  has_many :likes, dependent: :destroy

  has_many :following_relationships,
  class_name: "Relationship",
  foreign_key: "follower_id",
  dependent: :destroy
  has_many :followings, through: :following_relationships

  has_many :follower_relationships,
  class_name: "Relationship",
  foreign_key: "following_id",
  dependent: :destroy
  has_many :followers, through: :follower_relationships

  has_many :clips, dependent: :destroy

  has_many :notifications, dependent: :destroy

  has_many :comments, dependent: :destroy

  mount_uploader :image, ImageUploader

  validates :name, uniqueness: { case_sensitive: :false }, length: { minimum: 1, maximum: 20 }

  #引数にきたuserをフォローしているかを調べるメソッド
  def following?(other_user)
    self.following_relationships.find_by(following_id:other_user.id)
  end
#フォローするメソッド
  def follow!(other_user)
      self.following_relationships.create!(following_id:other_user.id)
  end
#フォロー解除するメソッド
  def unfollow!(other_user)
    self.following_relationships.find_by(following_id: other_user.id).destroy
  end
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  layout 'sub_layout'
  before_action :authenticate_user!, only: [:index, :edit, :update, :destroy, :new, :create]
  before_action :other_user, only: [:show, :following, :follower, :like, :clip]

  def index
    @user = User.find_by(id: current_user)
    @posts = current_user.posts.order('created_at DESC')
  end

  def show
    @posts = @user.posts.order('created_at DESC')
  end

  def edit
    @user = User.find_by(id: current_user)
  end

  def update
    @user = User.find_by(id: current_user)
    if @user.update(user_params)
      redirect_to user_index_path
    else
      render :edit
    end
  end

  def following
    @user_followings = @user.followings
    respond_to do |format|
      format.js
    end
  end

  def follower
    @user_followers = @user.followers
    respond_to do |format|
      format.js
    end
  end

  def like
    user_likes = @user.likes
    @posts = user_likes.map { |like| Post.find_by(id: like.post_id) }
    respond_to do |format|
      format.js
    end
  end

  def clip
    user_clips = @user.clips
    @posts = user_clips.map { |clip| Post.find_by(id: clip.post_id) }
    respond_to do |format|
      format.js
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :self_comment, :image)
  end

  def other_user
    @user = User.find_by(id: params[:id])
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
   def create
    super
   end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  protected
  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    root_path
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/user_helper.rb
module UserHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def user_self_comment_lim80(user)
    return unless user.self_comment
    if user.self_comment.length <= 80
      user.self_comment
    else
      user.self_comment.truncate(80)
    end
  end

  def current_user?(user)
    user == current_user
  end

end

app/views/user/_current_user_stats.html.erb
<p>フォロー数 <%= @current_user_followings %> 人</p>
<p>フォロワー数 <%= @current_user_followers %> 人</p>

app/views/user/_follow-form.html.erb
<% if current_user.following?(@user) %>
<p><a href="#" class="orange-button text-orange">フォロー</a></p>

app/views/user/_nav.html.erb
<!-- PC版 nav -->
<div class="userpage-nav sp-hidden">
  <div class="userpage-nav-content flex justify-content-around">
    <% if user_signed_in? %>
      <% if user == current_user %>
        <p class="userpage-nav-button"><%= link_to "投稿", user_index_path %><span class="post-number"><%= @user.posts.count %></span></p>
      <% else %>
        <p class="userpage-nav-button"><%= link_to "投稿", user_path(user) %><span class="clip-number"><%= user.posts.count %></span></p>
      <% end %>
    <% else %>
      <p class="userpage-nav-button"><%= link_to "投稿", user_path(user) %><span class="clip-number"><%= user.posts.count %></span></p>
    <% end %>
    <p class="userpage-nav-button"><%= link_to "フォロー", user_following_path(user), remote: true %><span class="clip-number"><%= user.followings.count %></span></p>
    <p class="userpage-nav-button"><%= link_to "フォロワー", user_follower_path(user), remote: true %><span class="clip-number"><%= user.followers.count %></span></p>
    <p class="userpage-nav-button"><%= link_to "クリップ", user_clip_path(user), remote: true %><span class="clip-number"><%= user.clips.count %></span></p>
    <% if user_signed_in? %>
      <% if user == current_user %>
        <div class="others-button accbox">
          <input type="checkbox" id="label2" class="cssacc" />
          <label for="label2" onclick="showOthers()" class="label2">その他</label>
          <span class="others" id="makeoOthers">
            <%= link_to "いいね", user_like_path(@user), remote: true %><br>
            <a href="#">下書き</a>
          </span>
        </div>
      <% else %>
        <p class="userpage-nav-button"><%= link_to "いいね", user_like_path(user), remote: true %><span class="clip-number"><%= user.likes.count %></span></p>
      <% end %>
    <% else %>
      <p class="userpage-nav-button"><%= link_to "いいね", user_like_path(user), remote: true %><span class="clip-number"><%= user.likes.count %></span></p>
    <% end %>
  </div>
</div>
<!-- /PC版 nav -->

<!-- SP版 nav -->
<div class="userpage-sp-nav sp-show">
  <div class="userpage-nav-content flex justify-content-between text-light-gray">
    <% if user_signed_in? %>
      <% if user == current_user %>
        <p class="userpage-sp-nav-button"><%= link_to "投稿", user_index_path %></p>
      <% else %>
        <p class="userpage-sp-nav-button"><%= link_to "投稿", user_path(user) %></p>
      <% end %>
    <% else %>
      <p class="userpage-sp-nav-button"><%= link_to "投稿", user_path(user) %></p>
    <% end %>
    <p class="userpage-sp-nav-button"><%= link_to "クリップ", user_clip_path(user), remote: true %></p>
    <p class="userpage-sp-nav-button"><%= link_to "いいね", user_like_path(user), remote: true %></p>
    <% if user_signed_in? %>
      <% if user == current_user %>
        <p class="userpage-sp-nav-button"><a href="#">下書き</a></p>
      <% end %>
    <% end %>
  </div>
</div>
<!-- /SP版 nav -->

app/views/user/_post.html.erb
<div class="box-shadow userpage-content-list-col">
  <div class="song-info-position">
    <%= link_to post_path(id:post.id) do %>
     <img src="<%= post.track_image%>" alt="" class="userpage-post-img">
    <% end %>
    <div class="song-info text-white sp-hidden">
      <p class="song-title"><%=fa_icon('user')%></i><%=post.artist_name %></p>
      <p class="artist"><%=fa_icon('dot-circle')%></i><%=post.track_name%></p>
    </div>
  </div>
  <div class="post-user flex sp-hidden">
    <% if post.user.image? %>
      <%= link_to image_tag(post.user.image, class: "user-icon user-icon-small"), user_path(post.user) %>
    <% else %>
      <%= link_to image_tag('default_img.png', class: "def-user-icon def-user-icon-small"), user_path(post.user) %>
    <% end %>
    <div class="post-info">
      <% if post.user == current_user %>
        <p class="user-name text-gray"><%= post.user.name %></p>
      <% else %>
        <p class="user-name text-gray"><%= link_to "#{post.user.name}", user_path(post.user) %></p>
      <% end %>
      <p><%= post.title %></p>
    </div>
  </div><!-- /post-user -->
  <hr class="m-0">
  <div class="action user-content-post-btn" id="post-content-action justify-content-around flex sp-hidden">
    <%=fa_icon('comment')%><p class="count-beside-btn"><%=post.comments.count%></p></i>
    <%= render partial: 'likes/like', locals: { post: post } %>
    <%= render partial: 'clips/clip', locals: { post: post} %>
    <i class="fas fa-external-link-alt"></i>
 </div>
</div>

app/views/user/_show_follow.html.erb
<%= @followings.each do |following| %>
  <p><%= following.name %></p>
  <p><%= following.email %></p>
  <% end %>

app/views/user/_user.html.erb
<div class="box-shadow userpage-content-list-col userpage-content-follow">
  <div>
    <% if user.image? %>
      <%= link_to image_tag(user.image, class: "user-icon user-icon-small"), user_path(user) %>
    <% else %>
      <%= link_to image_tag('default_img.png', class: "def-user-icon def-user-icon-small"), user_path(user) %>
    <% end %>
    <span id="follow-<%=user.id%>">
    <p><%= render partial:'relationships/follow',locals:{user:user} %></p>
    </span>
  </div>
  <div class="flex">
    <p class="user-name"><%= link_to "#{user.name}", user_path(user) %></p>
  </div><!-- /post-user -->
  <hr class="m-0">
  <div class="user-content-self-comment">
    <p class="text-gray"><%= user_self_comment_lim80(user) %></p>
  </div>
</div>

app/views/user/clip.js.erb
$("#userpage-content-render").html("<%= j(render partial: 'post', collection: @posts, as: 'post') %>")

app/views/user/edit.html.erb
<div class="post-page bg-white container profile-edit all">
  <% if @user.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for(@user) do |f| %>
    <div class="top-bar flex">
<!--       <p class="cancel mr-auto"><a href="#" class="text-gray">キャンセル</a></p>
 --><!--       <p><a href="#" class="orange-button text-white bg-orange save-button">保存</a></p> -->
      <div class="profile-submit"><%= f.submit "保存", class: "orange-button text-white bg-orange save-button profile-edit-btn", id: "profile-submit-btn" %></div>
    </div>
    <hr class="m-0">
      <div class="user-panel profile-icon">
        <div class="mb-2">
          <% if @user.image? %>
            <%= image_tag @user.image, class: "user-icon user-icon-superbig profile-img", id: "user-img-preview" %>
          <% else %>
            <%= image_tag 'default_img.png', class: "def-user-icon profile-img ", id: "user-img-preview" %>
          <% end %>
          <p>
            <%= f.label :image, "プロフィール写真を変更", class: "text-orange profile-edit-btn", for: "select-user-image" %>
            <%= f.file_field :image, id: "select-user-image" %>
          </p>
        </div>
      </div>
      <hr class="m-0">

      <table class="text-left profile-edit-table profile-table">
        <tbody>
          <tr class="border-bottom">
            <th class="user-edit-column">ユーザー名</th>
            <td><%= f.text_field :name, placeholder: "ニックネーム", class: "profile-input" %></td>
          </tr>
          <tr class="border-bottom">
            <th class="user-edit-column">自己紹介</th>
            <td><%= f.text_area :self_comment, class: "profile-input", id: "profile-input-self-comment" %></td>
          </tr>
          <tr class="border-bottom">
            <th class="user-edit-column">メールアドレス</th>
            <td><%= f.email_field :email, class: "profile-input" %></td>
          </tr>
          <!-- パスワード -->
    <!--       <tr>
            <th>***</th>
            <td>*********</td>
          </tr> -->
        </tbody>
      </table>
  <% end %>
</div>

app/views/user/follower.js.erb
$("#userpage-content-render").html("<%= j(render partial: 'user', collection: @user_followers, as: 'user') %>")

app/views/user/following.js.erb
$("#userpage-content-render").html("<%= j(render partial: 'user', collection: @user_followings, as: 'user') %>")

app/views/user/index.html.erb
<div class="all container userpage sp-container">
  <!-- user-panel -->
  <div class="user-panel">
    <div class="mb-2 flex justify-content-between">
      <% if @user.image? %>
        <%= image_tag @user.image, class: "user-icon user-icon-superbig" %>
      <% else %>
        <%= image_tag 'default_img.png', class: "def-user-icon def-user-icon-superbig" %>
      <% end %>
      <div class="user-explanation">
        <p class="user-name mr-auto"><%= @user.name %></p>
        <p class=""><%= @user.self_comment %></p>
      </div>
      <!-------------------------------------------------->
      <div class="user-panel-button">
        <label for="label1" class="label1" onclick="showButtonContents()"><span class="sp-hidden"><i class="fas fa-ellipsis-v"></i></span></label>
        <span class="button-contents" id="makeButtonContents">
          <%= link_to "プロフィール編集", edit_user_path(@user) %><br>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %><br>
<!--           <a href="#">キャンセル</a> -->
        </span>
      </div>
      <!-------------------------------------------------->
      <p><%= link_to "プロフィール編集", edit_user_path(@user), class: "orange-button profile-edit-button sp-show" %></p>
    </div>
    <!-- フォロー数 -->
    <div class="follow_follower-number sp-show">
      <p><%= @user.followings.count %><span class="text-light-gray">フォロー中</span>&emsp;<%= @user.followers.count %><span class="text-light-gray">フォロワー</span></p>
    </div>
    <!-- /フォロー数 -->
  </div><!-- /user-panel -->

  <%= render partial: 'nav', locals: { user: @user } %>

  <div class="userpage-content-list row" id="userpage-content-render"><!-- justify-content-between -->
    <%= render partial: "post", collection: @posts, as: 'post' %>
  </div>
</div>

app/views/user/like.js.erb
$("#userpage-content-render").html("<%= j(render partial: 'post', collection: @posts, as: 'post') %>")

app/views/user/show.html.erb
<div class="all container userpage sp-container">
  <!-- user-panel -->
  <div class="user-panel">
    <div class="mb-2 flex justify-content-between">
      <% if @user.image? %>
        <%= image_tag @user.image, class: "user-icon user-icon-superbig" %>
      <% else %>
        <%= image_tag 'default_img.png', class: "def-user-icon def-user-icon-superbig" %>
      <% end %>
      <div class="user-explanation">
        <p class="user-name mr-auto"><%= @user.name %></p>
        <p class=""><%= @user.self_comment %></p>
      </div>
      <!-------------------------------------------------->
      <div class="user-panel-button">
<!--         <label for="label1" class="label1" onclick="showButtonContents()"><span class="sp-hidden"><i class="fas fa-ellipsis-v"></i></span></label> -->
<!--         <span class="button-contents" id="makeButtonContents">
          <a href="#">ユーザーを報告</a><br>
          <a href="#">ブロック</a><br>
          <a href="#">キャンセル</a>
        </span> -->
      </div>
      <!-------------------------------------------------->
    </div>
    <span id="follow-<%=@user.id%>">
      <%= render partial:'relationships/follow',locals:{user:@user}%>
    </span>
    <!-- フォロー数 -->
    <div class="follow_follower-number sp-show">
      <p><%= @user.followings.count %><span class="text-light-gray">フォロー中</span>&emsp;<%= @user.followers.count %><span class="text-light-gray">フォロワー</span></p>
    </div>
    <!-- /フォロー数 -->
  </div><!-- /user-panel -->

  <%= render partial: 'nav', locals: { user: @user } %>

  <div class="userpage-content-list row" id="userpage-content-render"><!-- justify-content-between -->
    <%= render partial: 'post', collection: @posts, as: 'post' %>
  </div>
</div>