config/routes.rb
Rails.application.routes.draw do
  # devise_for :user, skip: :all, controllers: { passwords: 'passwords' }
  # devise_scope :user do
  #   post 'login', to: 'devise/sessions#create', as: :user_session
  #   delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
  #   post 'sign_in', to: 'devise/registrations#create', as: :user_registration
  #   get 'password/edit', to: 'users/passwords#edit', as: :edit_user_password
  #   patch 'password/edit', to: 'users/passwords#update'
  #   put 'password/edit', to: 'users/passwords#update'
  #   post 'password/edit', to: 'users/passwords#create',as: :user_password
  # end

  devise_for :users
  #devise パスワードを忘れた場合のメール処理
  if Rails.env.development? || Rails.env.staging?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "posts#index"
  resources :posts do
    resources :likes, only: [:create, :destroy]
    resources :clips, only: [:create, :destroy]
  end
  post '/posts/track', to: 'posts#track'
  get '/all_index', to: 'posts#all_index'
  resources :user
  resources :relationships, only: [:create,:destroy]
  resources :comments , only: [:create, :destroy]
  get 'user/:id/following', to: 'user#following', as: :user_following
  get 'user/:id/follower', to: 'user#follower', as: :user_follower
  get 'user/:id/like', to: 'user#like', as: :user_like
  get 'user/:id/clip', to: 'user#clip', as: :user_clip
  get 'rankings/post_ranking', to: 'rankings#post_ranking'
  get 'rankings/user_ranking', to: 'rankings#user_ranking'
  get 'searches/index', to: 'searches#index'
  get 'searches/more_posts', to: 'searches#more_posts'
  get 'searches/more_users', to: 'searches#more_users'
  get 'notifications/index', to: 'notifications#index'
  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get '/rules', to: 'policies#rules'
  get '/policy', to: 'policies#privacypolicy'
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  layout 'sub_layout'

  def index
  end

  def more_posts
  end

  def more_users
  end
end

app/views/searches/_search_form.html.erb
<%= form_tag searches_index_path, class: "header-search-form", method: :get, autocomplete: "off" do %>
  <%= text_field_tag(:q, '', class: "header-search-input bg-gray", placeholder: "投稿・ユーザーを検索") %>
  <label class="header-search-label"><i class="fas fa-search"></i></label>
  <% if user_signed_in? %>
    <%= link_to notifications_index_path, class: "bell mr-auto" do %>
      <i class="far fa-bell bg-gray"></i>
    <% end %>
  <% end %>
<% end %>

app/views/searches/_searched_post.html.erb
<div class="post-ranking-content">
  <div class="container pr-0">
    <div class="row">
      <div class="col-left col-md-3 p-0">
        <div class="post-image">
          <%= image_tag "#{ post.track_image }", class: "post-ranking-image" %>
          <div class="song-info text-white">
            <p class="song-title"><i class="far fa-user"></i>WAY OF GLORY</p>
            <p class="artist"><i class="far fa-dot-circle"></i>AAA</p>
          </div>
        </div><!-- /post-image -->
      </div>
      <div class="col-right col-md-9">
        <div class="post-user">
          <% if post.user.image? %>
            <%= link_to image_tag(post.user.image, class: "user-icon user-icon-mini", style: "height: 50px; width: 50px;"), user_path(post.user) %>
          <% else %>
            <%= link_to image_tag('default_img.png', class: "def-user-icon def-user-icon-mini", style: "height: 50px; width: 50px;"), user_path(post.user) %>
          <% end %>
          <p class="user-name text-gray"><a href="#"><%= post.user.name %></a></p>
          <p><%= post.title %></p>
        </div><!-- /post-user -->
        <div class="clear"></div>
        <p class="text text-gray"><%= post.text %></p>
      </div>
    </div><!-- /row -->
  </div><!-- /container -->
  <div class="action" id="post-content-action">
    <i class="far fa-comment"><p class="count-beside-btn">0</p></i>
    <%= render partial: 'likes/like', locals: { post: post } %>
    <%= render partial: 'clips/clip', locals: { post: post } %>
    <i class="fas fa-external-link-alt"></i>
  </div>
</div><!-- /post-ranking-content -->
<hr>

app/views/searches/_searched_user.html.erb
<div class="user-panel">
    <div class="flex mb-2">
        <% if user.image? %>
          <%= link_to image_tag(user.image, class: "user-icon user-icon-mini", style: "height: 50px; width: 50px;"), user_path(user) %>
        <% else %>
          <%= link_to image_tag('default_img.png', class: "def-user-icon def-user-icon-mini", style: "height: 50px; width: 50px;"), user_path(user) %>
        <% end %>
        <p class="user-name mr-auto"><a href="#"><%= user.name %></a></p>
        <p><a href="#" class="orange-button text-orange">フォロー</a></p>
    </div>
    <p class="user-explanation text-gray">
      <%= user.self_comment %>
    </p>
    <hr>
</div>

app/views/searches/index.html.erb
<div class="all container">
<p id="searched-result-title">検索結果："<%= @q %>"</p>
  <div class="row">
    <div class="col-md-8 main">
      <div class="box bg-white">
        <div class="box bg-white">
            <div class="ranking-post">
                <p class="ranking-post-title"><i class="far fa-user"></i>投稿</p>
                  <% if @q.empty? %>
                    <p>投稿は見つかりませんでした</p>
                  <% else %>
                    <% if @searched_posts.limit(10).last %>
                      <!-- 検索した投稿は10件まで表示される("もっと見る"で他の結果も表示される)-->
                      <%= render partial: 'searched_post', collection: @searched_posts.limit(10), as: 'post' %>
                    <% elsif @searched_posts.exists? %>
                      <!-- 検索した投稿は10件まで表示される("もっと見る"で他の結果も表示される)-->
                      <%= render partial: 'searched_post', collection: @searched_posts.limit(10), as: 'post' %>
                      <%= link_to "もっと見る", searches_more_posts_path, class: "more"%>
                    <% else %>
                      <p>投稿は見つかりませんでした</p>
                    <% end %>
                  <% end%>
            </div>
        </div>
    </div><!-- /col-md-8 main -->
  </div><!-- /row -->

  <div class="col-md-4 side-bar">
    <div class="box bg-white mb-3">
        <div class="ranking-user">
            <p class="ranking-user-title"><i class="far fa-user"></i>ユーザー</p>
              <% if @q.empty? %>
                <p>ユーザーは見つかりませんでした</p>
              <% else %>
                <% if @searched_users.limit(10).last %>
                  <!-- 検索したユーザーは10件まで表示される("もっと見る"で他の結果も表示される)-->
                  <%= render partial: 'searched_user', collection: @searched_users.limit(10), as: 'user' %>
                <% elsif @searched_users.exists? %>
                  <!-- 検索したユーザーは10件まで表示される("もっと見る"で他の結果も表示される)-->
                  <%= render partial: 'searched_user', collection: @searched_users.limit(10), as: 'user' %>
                  <%= link_to "もっと見る", searches_more_users_path, class: "more" %>
                <% else %>
                  <p>ユーザーは見つかりませんでした</p>
                <% end %>
              <% end %>
        </div>
      </div><!-- /box -->
    </div><!-- /box -->
  </div><!-- /col-md-4 side-bar bg-white -->
</div><!-- /container -->

app/views/searches/more_posts.html.erb
<div class="all container">
<p id="searched-result-title">検索結果</p>
  <div class="row">
    <div class="col-md-12">
      <div class="box bg-white">
        <div class="box bg-white">
            <div class="ranking-post">
              <p class="ranking-post-title"><i class="far fa-user"></i>投稿</p>
              <%= render partial: 'searched_post', collection: @searched_posts, as: 'post' %>
            </div>
        </div>
    </div><!-- /col-md-8 main -->
  </div><!-- /row -->
</div>

app/views/searches/more_users.html.erb
<div class="all container">
<p id="searched-result-title">検索結果</p>
  <div class="row">
    <div class="col-md-12">
      <div class="box bg-white">
        <div class="box bg-white">
            <div class="ranking-post">
              <p class="ranking-post-title"><i class="far fa-user"></i>ユーザー</p>
              <%= render partial: 'searched_user', collection: @searched_users, as: 'user' %>
            </div>
        </div>
    </div><!-- /col-md-8 main -->
  </div><!-- /row -->
</div>